### PR TITLE
Update DOCS.md

### PR DESCRIPTION
**Pull request by edgurgel**

### CODE REVIEW

**Comment by jackspirou** [comment]
@edgurgel can you `--rebase` since this branch is out of date?

**Comment by edgurgel** [comment]
Sure. I will soon!

**Comment by jackspirou** [comment]
Thank you!

**Comment by edgurgel** [comment]
done!

**Comment by jackspirou** [comment]
LGTM

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
