### PR TITLE
Remote graph caching

### PR DESCRIPTION
**Pull request by AKoetsier**
This is a cherrypick of the changes made to the drone-docker-plugin to improve caching of the docker build commands.

### CODE REVIEW

**Comment by AKoetsier** [comment]
This should fix #11 as well.

**Comment by nunofgs** [comment]
:+1: I really need this feature. Any news on this?

**Comment by fixe** [comment]
Tested locally and works.

**Comment by tboerger** [comment]
That should be also done for drone-docker and drone-gcr.

**Comment by nlf** [comment]
lgtm

**Comment by AKoetsier** [comment]
@tboerger this was already cherry picked from drone-docker.

**Comment by tboerger** [comment]
@AKoetsier than it should still be done for gcr :D

**Comment by tboerger** [comment]
LGTM

**Comment by tboerger** [comment]
Needs rebase.

**Comment by tboerger** [comment]
Still LGTM

**Comment by tboerger** [comment]
I have no idea why the build was successfull. I had to open https://github.com/drone-plugins/drone-ecr/pull/23 to resolve a naming issue.

**Pull request merged**
